In [1]:
# 라이브러리 import
from random import *
import pandas as pd
import math

In [2]:
# DataFrame에 시작점/속도/회전각 난수 대입하는 Function
# 시작점 -> (0,0)
# 속도 -> 30km/h ~ 80km/h 사이에 랜덤 생성
# 회전각 -> 10˚ ~ 80˚ 사이에 랜덤 생성

def createData(df, end):
    for i in range(end):
        df.loc[i] = [(0, 0), randint(30, 80), (randint(10, 80) * (math.pi/180))]

In [3]:
# 시작점/속도/회전각 속성 가지는 DataFrame 생성 (전부 다 임의의 값인 0 대입)
df = pd.DataFrame(data={'start':[0,0], 'speed':[0,0], 'angle':[0,0]})

# DataFrame에 instance값 삭제 -> 값은 없고 column만 있는 DataFrame으로 만들기 위해!
df = df[df.start != 0]

# 50,000개 임의의 데이터 생성_오래걸림;
createData(df, 50000)

In [4]:
# x = -rcosθ (좌회전이라 -붙음)
# y = rsinθ
# 도착점 (x,y) 계산하는 Function

def computeEnd(df):
    end = []
    for i in range(len(df)):
        angle = df['angle'][i]
        x = round(-(50 * math.cos(angle)), 3)
        y = round(50 * math.sin(angle), 3)
        end.append((x,y))
        
    endpoint = pd.Series(end)
    return endpoint

In [5]:
# endXY = pd.Series 타입
endXY = computeEnd(df)

In [6]:
# DataFrame에 새로운 column 'end'에 값 insert
df['end'] = endXY

In [7]:
df

        start  speed     angle                end
0      (0, 0)     77  1.204277  (-17.918, 46.679)
1      (0, 0)     53  0.890118  (-31.466, 38.857)
2      (0, 0)     40  0.942478  (-29.389, 40.451)
3      (0, 0)     44  1.326450  (-12.096, 48.515)
4      (0, 0)     76  0.872665  (-32.139, 38.302)
5      (0, 0)     39  0.750492    (-36.568, 34.1)
6      (0, 0)     31  0.802851  (-34.733, 35.967)
7      (0, 0)     80  0.959931  (-28.679, 40.958)
8      (0, 0)     51  0.977384   (-27.96, 41.452)
9      (0, 0)     47  1.274090  (-14.619, 47.815)
10     (0, 0)     72  0.349066  (-46.985, 17.101)
11     (0, 0)     53  0.226893  (-48.719, 11.248)
12     (0, 0)     46  0.453786   (-44.94, 21.919)
13     (0, 0)     54  0.663225  (-39.401, 30.783)
14     (0, 0)     72  0.471239     (-44.55, 22.7)
15     (0, 0)     60  0.209440  (-48.907, 10.396)
16     (0, 0)     78  1.099557     (-22.7, 44.55)
17     (0, 0)     54  0.383972   (-46.359, 18.73)
18     (0, 0)     53  0.471239     (-44.55, 22.7)
19     (0, 0)     73  1.169371  (-19.537, 46.025)
20     (0, 0)     33  0.994838  (-27.232, 41.934)
21     (0, 0)     76  0.296706  (-47.815, 14.619)
22     (0, 0)     76  1.012291  (-26.496, 42.402)
23     (0, 0)     50  0.349066  (-46.985, 17.101)
24     (0, 0)     49  0.174533    (-49.24, 8.682)
25     (0, 0)     63  0.558505  (-42.402, 26.496)
26     (0, 0)     77  0.226893  (-48.719, 11.248)
27     (0, 0)     56  0.698132  (-38.302, 32.139)
28     (0, 0)     32  0.401426  (-46.025, 19.537)
29     (0, 0)     37  0.750492    (-36.568, 34.1)
...       ...    ...       ...                ...
49970  (0, 0)     45  1.396263    (-8.682, 49.24)
49971  (0, 0)     34  0.890118  (-31.466, 38.857)
49972  (0, 0)     69  0.715585  (-37.735, 32.803)
49973  (0, 0)     72  1.134464  (-21.131, 45.315)
49974  (0, 0)     80  0.925025  (-30.091, 39.932)
49975  (0, 0)     44  0.680678  (-38.857, 31.466)
49976  (0, 0)     35  0.610865  (-40.958, 28.679)
49977  (0, 0)     40  0.942478  (-29.389, 40.451)
49978  (0, 0)     38  0.575959  (-41.934, 27.232)
49979  (0, 0)     55  0.820305    (-34.1, 36.568)
49980  (0, 0)     42  0.767945  (-35.967, 34.733)
49981  (0, 0)     79  1.256637  (-15.451, 47.553)
49982  (0, 0)     79  1.169371  (-19.537, 46.025)
49983  (0, 0)     66  0.750492    (-36.568, 34.1)
49984  (0, 0)     79  0.523599    (-43.301, 25.0)
49985  (0, 0)     42  0.663225  (-39.401, 30.783)
49986  (0, 0)     54  0.977384   (-27.96, 41.452)
49987  (0, 0)     43  0.436332  (-45.315, 21.131)
49988  (0, 0)     55  0.471239     (-44.55, 22.7)
49989  (0, 0)     39  1.308997  (-12.941, 48.296)
49990  (0, 0)     31  1.378810    (-9.54, 49.081)
49991  (0, 0)     73  0.261799  (-48.296, 12.941)
49992  (0, 0)     45  0.610865  (-40.958, 28.679)
49993  (0, 0)     78  0.959931  (-28.679, 40.958)
49994  (0, 0)     61  0.261799  (-48.296, 12.941)
49995  (0, 0)     44  0.750492    (-36.568, 34.1)
49996  (0, 0)     80  0.785398  (-35.355, 35.355)
49997  (0, 0)     64  0.575959  (-41.934, 27.232)
49998  (0, 0)     80  0.506145   (-43.731, 24.24)
49999  (0, 0)     33  1.343904  (-11.248, 48.719)

[50000 rows x 4 columns]

In [8]:
# 사고가 발생 유무를 계산해주는 Function

def computePassOrFail(df):
    PorF = []
    for i in range(len(df)):
        x2 = df['end'][i][0]
        y2 = df['end'][i][1]
        
        if (x2 < -20 and x2 > -40 and y2 > 20 and y2 < 35):
            PorF.append(0)  # 사고 X (Pass : 0)
        else:
            PorF.append(1)  # 사고 발생 (Fail : 1)
            
    success = pd.Series(PorF)
    return success

In [9]:
success = computePassOrFail(df)

In [10]:
success

0        1
1        1
2        1
3        1
4        1
5        0
6        1
7        1
8        1
9        1
10       1
11       1
12       1
13       0
14       1
15       1
16       1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25       1
26       1
27       0
28       1
29       0
        ..
49970    1
49971    1
49972    0
49973    1
49974    1
49975    0
49976    1
49977    1
49978    1
49979    1
49980    0
49981    1
49982    1
49983    0
49984    1
49985    0
49986    1
49987    1
49988    1
49989    1
49990    1
49991    1
49992    1
49993    1
49994    1
49995    0
49996    1
49997    1
49998    1
49999    1
Length: 50000, dtype: int64

In [11]:
df['PorF'] = success

In [12]:
# 1 : 사고 발생 (Fail)
# 0 : 사고 안남 (Pass)

df['PorF'].value_counts(normalize=True) * 100

1    88.852
0    11.148
Name: PorF, dtype: float64

In [14]:
# 여기서 부터 가라침
# 원래는 PorF = 1 인 것만 추출해야함 BUT 사고가 너무 많이 일어나서(88%) 순서 바꿈

df = df[df['PorF'] == 0]

In [15]:
df

        start  speed     angle                end  PorF
5      (0, 0)     39  0.750492    (-36.568, 34.1)     0
13     (0, 0)     54  0.663225  (-39.401, 30.783)     0
27     (0, 0)     56  0.698132  (-38.302, 32.139)     0
29     (0, 0)     37  0.750492    (-36.568, 34.1)     0
35     (0, 0)     31  0.680678  (-38.857, 31.466)     0
53     (0, 0)     40  0.663225  (-39.401, 30.783)     0
55     (0, 0)     39  0.698132  (-38.302, 32.139)     0
57     (0, 0)     46  0.663225  (-39.401, 30.783)     0
61     (0, 0)     64  0.680678  (-38.857, 31.466)     0
62     (0, 0)     44  0.715585  (-37.735, 32.803)     0
68     (0, 0)     43  0.645772  (-39.932, 30.091)     0
83     (0, 0)     79  0.767945  (-35.967, 34.733)     0
87     (0, 0)     71  0.750492    (-36.568, 34.1)     0
111    (0, 0)     63  0.767945  (-35.967, 34.733)     0
113    (0, 0)     43  0.767945  (-35.967, 34.733)     0
116    (0, 0)     55  0.663225  (-39.401, 30.783)     0
133    (0, 0)     56  0.698132  (-38.302, 32.139)     0
135    (0, 0)     31  0.680678  (-38.857, 31.466)     0
136    (0, 0)     74  0.750492    (-36.568, 34.1)     0
141    (0, 0)     58  0.733038  (-37.157, 33.457)     0
148    (0, 0)     68  0.767945  (-35.967, 34.733)     0
156    (0, 0)     61  0.750492    (-36.568, 34.1)     0
165    (0, 0)     31  0.767945  (-35.967, 34.733)     0
174    (0, 0)     69  0.715585  (-37.735, 32.803)     0
181    (0, 0)     34  0.767945  (-35.967, 34.733)     0
188    (0, 0)     35  0.750492    (-36.568, 34.1)     0
196    (0, 0)     55  0.767945  (-35.967, 34.733)     0
205    (0, 0)     66  0.663225  (-39.401, 30.783)     0
208    (0, 0)     40  0.715585  (-37.735, 32.803)     0
236    (0, 0)     44  0.680678  (-38.857, 31.466)     0
...       ...    ...       ...                ...   ...
49808  (0, 0)     41  0.733038  (-37.157, 33.457)     0
49819  (0, 0)     74  0.733038  (-37.157, 33.457)     0
49824  (0, 0)     54  0.698132  (-38.302, 32.139)     0
49825  (0, 0)     71  0.733038  (-37.157, 33.457)     0
49830  (0, 0)     66  0.680678  (-38.857, 31.466)     0
49838  (0, 0)     44  0.750492    (-36.568, 34.1)     0
49842  (0, 0)     37  0.733038  (-37.157, 33.457)     0
49848  (0, 0)     59  0.680678  (-38.857, 31.466)     0
49850  (0, 0)     79  0.733038  (-37.157, 33.457)     0
49856  (0, 0)     74  0.680678  (-38.857, 31.466)     0
49858  (0, 0)     43  0.750492    (-36.568, 34.1)     0
49864  (0, 0)     46  0.750492    (-36.568, 34.1)     0
49866  (0, 0)     70  0.715585  (-37.735, 32.803)     0
49872  (0, 0)     30  0.698132  (-38.302, 32.139)     0
49873  (0, 0)     36  0.680678  (-38.857, 31.466)     0
49876  (0, 0)     79  0.680678  (-38.857, 31.466)     0
49878  (0, 0)     53  0.733038  (-37.157, 33.457)     0
49900  (0, 0)     52  0.698132  (-38.302, 32.139)     0
49911  (0, 0)     78  0.680678  (-38.857, 31.466)     0
49916  (0, 0)     55  0.698132  (-38.302, 32.139)     0
49927  (0, 0)     61  0.715585  (-37.735, 32.803)     0
49935  (0, 0)     69  0.680678  (-38.857, 31.466)     0
49960  (0, 0)     77  0.715585  (-37.735, 32.803)     0
49961  (0, 0)     67  0.767945  (-35.967, 34.733)     0
49972  (0, 0)     69  0.715585  (-37.735, 32.803)     0
49975  (0, 0)     44  0.680678  (-38.857, 31.466)     0
49980  (0, 0)     42  0.767945  (-35.967, 34.733)     0
49983  (0, 0)     66  0.750492    (-36.568, 34.1)     0
49985  (0, 0)     42  0.663225  (-39.401, 30.783)     0
49995  (0, 0)     44  0.750492    (-36.568, 34.1)     0

[5574 rows x 5 columns]

In [18]:
# index값 다시 세팅
df = df.reset_index()
del df['index']  # 쓸모없는 column이라 삭제
df

      level_0   start  speed     angle                end  PorF
0           0  (0, 0)     39  0.750492    (-36.568, 34.1)     0
1           1  (0, 0)     54  0.663225  (-39.401, 30.783)     0
2           2  (0, 0)     56  0.698132  (-38.302, 32.139)     0
3           3  (0, 0)     37  0.750492    (-36.568, 34.1)     0
4           4  (0, 0)     31  0.680678  (-38.857, 31.466)     0
5           5  (0, 0)     40  0.663225  (-39.401, 30.783)     0
6           6  (0, 0)     39  0.698132  (-38.302, 32.139)     0
7           7  (0, 0)     46  0.663225  (-39.401, 30.783)     0
8           8  (0, 0)     64  0.680678  (-38.857, 31.466)     0
9           9  (0, 0)     44  0.715585  (-37.735, 32.803)     0
10         10  (0, 0)     43  0.645772  (-39.932, 30.091)     0
11         11  (0, 0)     79  0.767945  (-35.967, 34.733)     0
12         12  (0, 0)     71  0.750492    (-36.568, 34.1)     0
13         13  (0, 0)     63  0.767945  (-35.967, 34.733)     0
14         14  (0, 0)     43  0.767945  (-35.967, 34.733)     0
15         15  (0, 0)     55  0.663225  (-39.401, 30.783)     0
16         16  (0, 0)     56  0.698132  (-38.302, 32.139)     0
17         17  (0, 0)     31  0.680678  (-38.857, 31.466)     0
18         18  (0, 0)     74  0.750492    (-36.568, 34.1)     0
19         19  (0, 0)     58  0.733038  (-37.157, 33.457)     0
20         20  (0, 0)     68  0.767945  (-35.967, 34.733)     0
21         21  (0, 0)     61  0.750492    (-36.568, 34.1)     0
22         22  (0, 0)     31  0.767945  (-35.967, 34.733)     0
23         23  (0, 0)     69  0.715585  (-37.735, 32.803)     0
24         24  (0, 0)     34  0.767945  (-35.967, 34.733)     0
25         25  (0, 0)     35  0.750492    (-36.568, 34.1)     0
26         26  (0, 0)     55  0.767945  (-35.967, 34.733)     0
27         27  (0, 0)     66  0.663225  (-39.401, 30.783)     0
28         28  (0, 0)     40  0.715585  (-37.735, 32.803)     0
29         29  (0, 0)     44  0.680678  (-38.857, 31.466)     0
...       ...     ...    ...       ...                ...   ...
5544     5544  (0, 0)     41  0.733038  (-37.157, 33.457)     0
5545     5545  (0, 0)     74  0.733038  (-37.157, 33.457)     0
5546     5546  (0, 0)     54  0.698132  (-38.302, 32.139)     0
5547     5547  (0, 0)     71  0.733038  (-37.157, 33.457)     0
5548     5548  (0, 0)     66  0.680678  (-38.857, 31.466)     0
5549     5549  (0, 0)     44  0.750492    (-36.568, 34.1)     0
5550     5550  (0, 0)     37  0.733038  (-37.157, 33.457)     0
5551     5551  (0, 0)     59  0.680678  (-38.857, 31.466)     0
5552     5552  (0, 0)     79  0.733038  (-37.157, 33.457)     0
5553     5553  (0, 0)     74  0.680678  (-38.857, 31.466)     0
5554     5554  (0, 0)     43  0.750492    (-36.568, 34.1)     0
5555     5555  (0, 0)     46  0.750492    (-36.568, 34.1)     0
5556     5556  (0, 0)     70  0.715585  (-37.735, 32.803)     0
5557     5557  (0, 0)     30  0.698132  (-38.302, 32.139)     0
5558     5558  (0, 0)     36  0.680678  (-38.857, 31.466)     0
5559     5559  (0, 0)     79  0.680678  (-38.857, 31.466)     0
5560     5560  (0, 0)     53  0.733038  (-37.157, 33.457)     0
5561     5561  (0, 0)     52  0.698132  (-38.302, 32.139)     0
5562     5562  (0, 0)     78  0.680678  (-38.857, 31.466)     0
5563     5563  (0, 0)     55  0.698132  (-38.302, 32.139)     0
5564     5564  (0, 0)     61  0.715585  (-37.735, 32.803)     0
5565     5565  (0, 0)     69  0.680678  (-38.857, 31.466)     0
5566     5566  (0, 0)     77  0.715585  (-37.735, 32.803)     0
5567     5567  (0, 0)     67  0.767945  (-35.967, 34.733)     0
5568     5568  (0, 0)     69  0.715585  (-37.735, 32.803)     0
5569     5569  (0, 0)     44  0.680678  (-38.857, 31.466)     0
5570     5570  (0, 0)     42  0.767945  (-35.967, 34.733)     0
5571     5571  (0, 0)     66  0.750492    (-36.568, 34.1)     0
5572     5572  (0, 0)     42  0.663225  (-39.401, 30.783)     0
5573     5573  (0, 0)     44  0.750492    (-36.568, 34.1)     0

[5574 rows x 6 columns]

In [20]:
del df['level_0']  # 쓸모없는 column이라 삭제

In [21]:
df.to_csv("simulationData.csv", index=False)

In [22]:
df

       start  speed     angle                end  PorF
0     (0, 0)     39  0.750492    (-36.568, 34.1)     0
1     (0, 0)     54  0.663225  (-39.401, 30.783)     0
2     (0, 0)     56  0.698132  (-38.302, 32.139)     0
3     (0, 0)     37  0.750492    (-36.568, 34.1)     0
4     (0, 0)     31  0.680678  (-38.857, 31.466)     0
5     (0, 0)     40  0.663225  (-39.401, 30.783)     0
6     (0, 0)     39  0.698132  (-38.302, 32.139)     0
7     (0, 0)     46  0.663225  (-39.401, 30.783)     0
8     (0, 0)     64  0.680678  (-38.857, 31.466)     0
9     (0, 0)     44  0.715585  (-37.735, 32.803)     0
10    (0, 0)     43  0.645772  (-39.932, 30.091)     0
11    (0, 0)     79  0.767945  (-35.967, 34.733)     0
12    (0, 0)     71  0.750492    (-36.568, 34.1)     0
13    (0, 0)     63  0.767945  (-35.967, 34.733)     0
14    (0, 0)     43  0.767945  (-35.967, 34.733)     0
15    (0, 0)     55  0.663225  (-39.401, 30.783)     0
16    (0, 0)     56  0.698132  (-38.302, 32.139)     0
17    (0, 0)     31  0.680678  (-38.857, 31.466)     0
18    (0, 0)     74  0.750492    (-36.568, 34.1)     0
19    (0, 0)     58  0.733038  (-37.157, 33.457)     0
20    (0, 0)     68  0.767945  (-35.967, 34.733)     0
21    (0, 0)     61  0.750492    (-36.568, 34.1)     0
22    (0, 0)     31  0.767945  (-35.967, 34.733)     0
23    (0, 0)     69  0.715585  (-37.735, 32.803)     0
24    (0, 0)     34  0.767945  (-35.967, 34.733)     0
25    (0, 0)     35  0.750492    (-36.568, 34.1)     0
26    (0, 0)     55  0.767945  (-35.967, 34.733)     0
27    (0, 0)     66  0.663225  (-39.401, 30.783)     0
28    (0, 0)     40  0.715585  (-37.735, 32.803)     0
29    (0, 0)     44  0.680678  (-38.857, 31.466)     0
...      ...    ...       ...                ...   ...
5544  (0, 0)     41  0.733038  (-37.157, 33.457)     0
5545  (0, 0)     74  0.733038  (-37.157, 33.457)     0
5546  (0, 0)     54  0.698132  (-38.302, 32.139)     0
5547  (0, 0)     71  0.733038  (-37.157, 33.457)     0
5548  (0, 0)     66  0.680678  (-38.857, 31.466)     0
5549  (0, 0)     44  0.750492    (-36.568, 34.1)     0
5550  (0, 0)     37  0.733038  (-37.157, 33.457)     0
5551  (0, 0)     59  0.680678  (-38.857, 31.466)     0
5552  (0, 0)     79  0.733038  (-37.157, 33.457)     0
5553  (0, 0)     74  0.680678  (-38.857, 31.466)     0
5554  (0, 0)     43  0.750492    (-36.568, 34.1)     0
5555  (0, 0)     46  0.750492    (-36.568, 34.1)     0
5556  (0, 0)     70  0.715585  (-37.735, 32.803)     0
5557  (0, 0)     30  0.698132  (-38.302, 32.139)     0
5558  (0, 0)     36  0.680678  (-38.857, 31.466)     0
5559  (0, 0)     79  0.680678  (-38.857, 31.466)     0
5560  (0, 0)     53  0.733038  (-37.157, 33.457)     0
5561  (0, 0)     52  0.698132  (-38.302, 32.139)     0
5562  (0, 0)     78  0.680678  (-38.857, 31.466)     0
5563  (0, 0)     55  0.698132  (-38.302, 32.139)     0
5564  (0, 0)     61  0.715585  (-37.735, 32.803)     0
5565  (0, 0)     69  0.680678  (-38.857, 31.466)     0
5566  (0, 0)     77  0.715585  (-37.735, 32.803)     0
5567  (0, 0)     67  0.767945  (-35.967, 34.733)     0
5568  (0, 0)     69  0.715585  (-37.735, 32.803)     0
5569  (0, 0)     44  0.680678  (-38.857, 31.466)     0
5570  (0, 0)     42  0.767945  (-35.967, 34.733)     0
5571  (0, 0)     66  0.750492    (-36.568, 34.1)     0
5572  (0, 0)     42  0.663225  (-39.401, 30.783)     0
5573  (0, 0)     44  0.750492    (-36.568, 34.1)     0

[5574 rows x 5 columns]